-- =============================================================================
-- 01_concepts.sql — Read-only notes (reference). Not executed by the Java app.
-- =============================================================================
-- Mental model:
--
--   Spark (JdbcCatalog)
--     CREATE / INSERT Iceberg tables
--           |
--           +-- pointer (table → metadata.json) -->  PostgreSQL iceberg_tables
--           +-- metadata + Parquet files --------->  MinIO s3://warehouse/
--
--   Java reads metadata_location from Postgres
--           |
--           v
--   DuckDB iceberg_scan(exact metadata.json) + VIEW
--           |
--           v
--   Java JDBC  -->  CSV reports
--
-- Do not iceberg_scan the table root directory: JdbcCatalog does not write
-- version-hint.text. The catalog pointer in Postgres is the current snapshot.
-- =============================================================================
