-- =============================================================================
-- 01_concepts.sql — Read-only notes (reference). Not executed by the Java app.
-- =============================================================================
-- Mental model:
--
--   Spark (JdbcCatalog)
--     CREATE / INSERT Iceberg tables
--           |
--           +-- pointer (table → metadata.json) -->  PostgreSQL iceberg_tables
--           +-- metadata + Parquet files --------->  MinIO s3://warehouse/
--
--   Java reads metadata_location from Postgres
--           |
--           v
--   DuckDB iceberg_scan(exact metadata.json) + VIEW
--           |
--           v
--   Java JDBC  -->  CSV reports
--
-- Do not iceberg_scan the table root directory: JdbcCatalog does not write
-- version-hint.text. The catalog pointer in Postgres is the current snapshot.
--
-- Layered SQL (see 03_layered.sql):
--   VIEW        = named logical step; DuckDB can still inline it
--   TEMP TABLE  = materialize only when the layer is reused or must be checksummed
--   Do not fold latest-date + OPEN + join + two reports into one WITH
--
-- Observe (OBSERVE=1 or --observe): dump Iceberg snapshots / manifests / files
-- and SELECT * from named layers. Demo tables only.
-- =============================================================================
